config/routes.rb
Rails.application.routes.draw do

  root to: 'users#home'

  get '/login', to: 'sessions#new', as: 'login'
  # log in user
  post '/sessions', to: 'sessions#create', as: 'sessions'
  # log out user
  delete '/sessions', to: 'sessions#destroy', as: 'logout'

  # get '/pets/:id/story', to: 'pets#story', as: 'story'

  get '/pets/:id/care', to: 'pets#care', as: 'pet_care'

  post '/pets/:id/action', to: 'pets#action'

  resources :users, only: [:new, :create, :show]

  resources :pets, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :story
  serialize :results, Hash
end

app/models/personal_event.rb
class PersonalEvent < ApplicationRecord
  serialize :results, Hash
end

app/models/personality.rb
class Personality < ApplicationRecord
  belongs_to :pet

  @@types = ['brave', 'curious', 'social']

  def self.types
    @@types
  end

  def self.generate_random(pet_object)
    # does not save
    new_personality = self.new
    new_personality.pet = pet_object
    new_personality.pet_type = self.types.sample
    new_personality
  end

  def self.set_personality(pet_type, pet_object)
    # does save
    new_personality = self.new
    new_personality.pet = pet_object
    new_personality.pet_type = pet_type
    new_personality.save
    new_personality
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :species
  has_one :story
  has_many :histories, through: :story
  has_one :personality

  def new_story
    @story = Story.new
    @story.pet = self
  end

  def self.generate_random
    random_pet = Pet.new(name: Faker::Pokemon.name)
    random_pet.personality = Personality.generate_random(random_pet)
    random_pet.species = Species.generate_random
    random_pet.picture = Species.generate_picture(random_pet.species.name)
    random_pet.new_story
    random_pet
  end

  def display_hunger
    case self.hunger
    when (-500..-10)
      self.hunger = -10
      self.save
      "Your pet is EXTREMELY hungry, feed it!"
    when (-9..0)
      "Your pet is really hungry."
    when (1..10)
       "Your pet isn't hungry."
    when (11..20)
       "Your pet is full."
    when (21..500)
      if self.hunger > 30
        self.hunger = 30
        self.save
      end
      "Your pet is stuffed!"
    end
  end

  def display_happiness
    case self.happiness
    when (-500..-10)
      self.happiness = -10
      self.save
       "Your pet is EXTREMELY sad, cheer it up!"
    when (-9..0)
       "Your pet is really sad."
    when (1..10)
       "Your pet is mellow."
    when (11..20)
       "Your pet is happy!"
    when (21..500)
      if self.happiness > 30
        self.happiness = 30
        self.save
      end
       "Your pet is living the life!"
    end
  end

  def display_hygiene
    case self.hygiene
    when (-500..-10)
      self.hygiene = -10
      self.save
      "Your pet is EXTREMELY filthy, give it a bath!"
    when (-9..0)
      "Your pet is dirty."
    when (1..10)
      "Your pet is clean."
    when (11..20)
      "Your pet is sparkling!"
    when (21..500)
      if self.hygiene > 30
        self.hygiene = 30
        self.save
      end
      "Your pet is shining!"
    end
  end

  def play
    StoryUpdate.new(self).update_play
  end

  def wash
    StoryUpdate.new(self).update_wash
  end

  def feed
    StoryUpdate.new(self).update_feed
  end

  def explore
    StoryUpdate.new(self).manual_random_event
  end

  def fun
    StoryUpdate.new(self).update_story_personality
  end



end

app/models/random_event.rb
class RandomEvent < ApplicationRecord
    serialize :results, Hash
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :pets

  @@types = ['cat','dog','rock']

  def self.types
    @@types
  end

  # returns image path based on type
  def self.generate_picture(type)
    photo_path = Dir[ "app/assets/images/#{type.pluralize}/*.jpg" ].sample
    photo_path.slice! "app/assets/images/"
    photo_path
  end

  def self.generate_random
    new_species = self.new
    new_species.name = self.types.sample
    new_species
  end

  def self.set_species(type)
    new_species = self.new
    new_species.name = type
    new_species.save
    new_species
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :pet
  has_many :histories
  serialize :readable_history, Array





  def update_readable_history

    self.readable_history = []

    new_history = History.select do |event|
      event.story_id == self.id
    end
    new_history.sort_by {|event| event.event_time}.each do |story_item|
      self.readable_history << story_item
    end


  end




end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      redirect_to login_path
    end
  end


  def logged_in?
    !!current_user
  end


  def authorized
    if logged_in?

    else
      redirect_to login_path
    end
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :find_pet, only: [:show, :story, :care, :action]

  def new
    @pet = Pet.generate_random
  end

  def create
    @pet = Pet.new(name: pet_params[:name])
    @pet.personality = Personality.set_personality(pet_params[:personality], @pet)
    @pet.species = Species.set_species(pet_params[:species])
    @pet.user = current_user
    @pet.picture = pet_params[:picture]
    @pet.new_story
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def show
    @story = StoryUpdate.new(@pet).perform
    @pet.story.update_readable_history
  end

  def care
  end

  def action
    @action = pet_params[:action].downcase
    @pet.send(@action)

    redirect_to pet_path(@pet)
  end


private

  def pet_params
    params.require(:pet).permit(:name, :personality, :action, :species, :picture)
  end

  def find_pet
    @pet = Pet.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user
  end

  def create
    #lets look up a user
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      # let them in redirect_to some page
    else
      # couldnt log in
      
      render :new
    end

  end


  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end



end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController


  StoryUpdate.new({})
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
    if session[:user_id]
      redirect_to user_path(current_user)
    end
  end


  def show
    @user = current_user
    # @user = params[:id] This is only for testing
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coledatchi</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="light-green">
      <div class="container">
        <div class="nav-wrapper green">
          <a href="#!" class="brand-logo">Logo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a class="waves-effect waves-light green btn-large" href="#">Home</a></li>
            <li><a class="waves-effect waves-light green btn-large" href="#">Your Pet</a></li>
            <li><a class="waves-effect waves-light green btn-large" href="#">Logout</a></li>


          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a class="waves-effect waves-light green btn-large" href="#">Home</a></li>
            <li><a class="waves-effect waves-light green btn-large" href="#">Your Pet</a></li>
            <li><a class="waves-effect waves-light green btn-large" href="#">Logout</a></li>
            
          </ul>
        </div>
      </div>
      </nav>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>

    <script type="text/javascript">
      $(document).ready(function{
         $(".button-collapse").sideNav();
      });
    </script>
  </body>
</html>

app/views/pets/care.html.erb
<%= form_tag "/pets/#{@pet.id}/action", method: :post do %>
  <%= label_tag "What do you want to do with your pet?" %>
  <%= select_tag "pet[action]", options_for_select(["Play","Wash","Feed","Explore","Fun"]) %>
  <%= submit_tag "Choose" %>
<% end %>

app/views/pets/new.html.erb
<!-- This page is going to be the adopt a pet page. We should generate a list of pets to adopt -->
<p><%= button_to "Find New Random Pet", new_pet_path, method: 'get' %></p>
<%= image_tag( @pet.picture, :alt => @pet.name) %>
<ul>
<%= form_for @pet do |f| %>
  <li><%= f.label "What do you want to name your pet?" %></li>
  <ul>
    <li><%= f.text_field :name %></li>
  </ul>
  <li><%= f.label :personality %></li>
  <ul>
    <li><%= f.text_field :personality, value: @pet.personality.pet_type, :readonly => true %></li>
  </ul>
  <li><%= f.label :species %></li>
  <ul>
    <li><%= f.text_field :species, value: @pet.species.name,:readonly => true %></li>
  </ul>
  <%= f.hidden_field :picture %>
  <p><%= f.submit "Adopt Pet" %></p>
<% end %>
</ul>

app/views/pets/show.html.erb
<div class="center-align">
  <%= image_tag( @pet.picture, :alt => @pet.name, class: "circle")%>

</div>
<div role="main" class="main">



<div class="row">
<div class="col s6">
<ul class="collection">
  <li class="collection-item_stat valign-wrapper">
    <img src="/stats/user-name.svg" alt="" class="circle">
      <span class="title">Name:</span>
      <%= @pet.name %>
  </li>
  <li class="collection-item_stat valign-wrapper ">
    <img src="/stats/dog-in-front-of-a-man.svg" alt="" class="circle">
      <span class="title">Owner:</span>
      <%= @pet.user.name %>
  </li>
  <li class="collection-item_stat valign-wrapper">
    <img src="/stats/hearts-outline-icon.svg" alt="" class="circle">
      <span class="title">Happiness:</span>
      <%= @pet.happiness %>
  </li>
  <li class="collection-item_stat valign-wrapper">
        <img src="/stats/001-soap.svg" alt="" class="circle">
        <span class="title">Hygiene:</span>
        <%= @pet.hygiene %>
  </li>
  <li class="collection-item_stat valign-wrapper">
        <img src="/stats/002-turkey.svg" alt="" class="circle">
        <span class="title">Hunger:</span>
        <%= @pet.hunger %>
  </li>
  <li class="collection-item_stat valign-wrapper">
        <img src="/stats/brain-in-head.svg" alt="" class="circle">
        <span class="title">Personality:</span>
        <%= @pet.personality.pet_type %>
  </li>
  <li class="collection-item_stat valign-wrapper">
        <img src="/stats/003-two.svg" alt="" class="circle">
        <span class="title">Species:</span>
        <%= @pet.species.name %>
  </li>
</ul>

</div>



       <div class="col s6">
         <h1>History</h1>
         <div class="card light-green">
           <div class="card-content white-text ">
             <ul>
             <% @pet.story.readable_history.each do |event| %>
             <li><%= "#{event.description} on #{event.event_time.localtime.strftime("%A, %d on %I:%M%p")}" %></li>
             <% end %>
             </ul>
           </div>
         </div>
         <h1>Right Now</h1>

         <div class="collection">


        <a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">#</i></a>
        <font size=5> <%= @pet.display_happiness %> </font><br>
        <a class="btn-floating btn-large waves-effect waves-light blue"><i class="material-icons">#</i></a>
        <font size=5> <%= @pet.display_hygiene %> </font><br>
        <a class="btn-floating btn-large waves-effect waves-light green"><i class="material-icons">#</i></a>
        <font size=5> <%= @pet.display_hunger %> </font><br>

        </div>
      </div>



 </div>

<%= link_to "Take care of your pet", pet_care_path(@pet) %>
<p><%= link_to 'Logout', sessions_path, method: :delete, data: {confirm: 'Are you sure?'} %></p>

<%= link_to "User Page", user_path(@pet.user) %>
</div>

app/views/pets/story.html.erb
<%= @story %>

app/views/users/home.html.erb
<h1>Home</h1>
<h3>Welcome to coledatchi</h3>

<p><%= link_to "Sign Up", new_user_path %></p>
<p><%= link_to "Login", login_path %></p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<p>Your Name</p>
<%= @user.name %>
<p>Your Email</p>
<%= @user.email %>
<p>Created At</p>
<%= @user.created_at %>
<p>Pet</p>
<% if @user.pets.last %>
  <%=link_to @user.pets.last.name, pet_path(@user.pets.last) %>
<% else %>
  <%= link_to "Create a Pet", new_pet_path %>
<% end %>


<p><%= link_to 'Logout', sessions_path, method: :delete, data: {confirm: 'Are you sure?'} %></p>